### ISSUE TITLE
Maybe Add a forked version on the Blue Iris 4?

### ISSUE THREAD

**Issue by MapGuy11** [jshridha/docker-blueiris#12]
Hello! Great work I was wondering if you could make a version with the Blue Iris 4 version.

Here is exe link: https://blueirissoftware.com/BlueIris_48603.exe

**Comment by jshridha** [comment]
Thanks for the feature request! I added this in the dev version of the container. Just set the environmental variable BLUEIRIS_VERSION=4 and it'll download/install the exe you provided. Thanks again!
