### ISSUE TITLE
Blue Iris install does not lauch.  Can be launched manually for set up

### ISSUE THREAD

**Issue by dinki** [jshridha/docker-blueiris#2]
Hi and thanks for the great docker!  Initially I could not get BI install to launch.  I did manage to get it up and running by:

docker exec -it BlueIris /bin/bash
wget http://blueirissoftware.com/blueiris.exe
./blueiris.sh

I initially tried just running the blueiris.sh file but it complained that the blueiris.exe didn't exist so I grabbed it with wget and then launched the script and things started working.

I'm not sure where the problem is with the script but I'm guessing it is just not downloading the software and that causes things to break.

Everything seems to be working except for web access.  I got this error when trying to use authentication:

https://i.imgur.com/Pju78Y8.png

I installed UI3 and was able to get in fine but only if I keep authentication off which is not ideal.  Any ideas on what could be causing this problem?

**Comment by jshridha** [comment]
This should be fixed now.
