### ISSUE TITLE
UI3 login page is not installed

### ISSUE THREAD

**Issue by TonyBrobston** [jshridha/docker-blueiris#26]
Upon startup or restart, `www` does not have `login.htm`:
```
ls /root/prefix32/drive_c/Program\ Files/Blue\ Iris\ 5/www/
applet  clappr  livestream.htm  timeout.htm  ui3  ui3.htm  xlogin.htm
```
When navigating to http://[your machine's ip here]:81/login.htm?page=%2F a 404 is returned, further confirming that this `.htm` file is missing.

A short-term workaround is to 
```
rm -rf /root/prefix32/drive_c/Program\ Files/Blue\ Iris\ 5/www/* && unzip /root/prefix32/drive_c/Program\ Files/Blue\ Iris\ 5/ui3.zip -d /root/prefix32/drive_c/Program\ Files/Blue\ Iris\ 5/www/
``` 
Referenced here: https://github.com/jshridha/docker-blueiris/issues/13

However this workaround is only good until the container is restarted, at which point the workaround will need run again; making this not a viable solution.

**Comment by TonyBrobston** [comment]
I also tested this on Windows and it works as expected.

**Comment by TonyBrobston** [comment]
I think a potential workaround that may work long-term, would be to add another program to `supervisord.conf` that deletes all the contents of `www` and then unzips `ui3.zip` into `www`. I'm going to experiment with this idea.

**Comment by TonyBrobston** [comment]
This will get closed when https://github.com/jshridha/docker-blueiris/pull/27 is merged.

**Comment by kloknibor** [comment]
I'm currently downloading the UI3 interface from here : https://github.com/bp2008/ui3 and put it in the www folder. This does seem to fix the problem longterm as well. But would it maybe be nice to get the latest ui3 version from here? Or you rather use the one that's shipped/packaged with blue iris?

**Comment by leonowski** [comment]
I didn't realize that the ui3 stuff was an open project.  We can certainly just take it from that project and drop it in instead of the the version in the installer.  I can go either way.  We can set it up in a way so that it always pulls the latest from github and extracts on every container restart.

Thoughts?

**Comment by TonyBrobston** [comment]
@leonowski I wonder a few things:
1. Is BlueIris.exe updated with the latest ui3 as ui3 has changes merged to master?
2. Is there a chance Blue Iris will stop putting ui3.zip in the `Blue Iris 5` directory?

Seems like having the latest from GitHub would be nice and would reduce future risk of ui3 breaking if BlueIris.exe is updated and ui3 is not included. However, at the moment neither is probably a problem; so while this would probably be a good change it's probably lower priority.

I think we should close this issue and if we want other changes, open a new issue and reference this one.
