### ISSUE TITLE
Inspect/Detect no longer works

### ISSUE THREAD

**Issue by jshridha** [jshridha/docker-blueiris#39]
I just started trying to dev on this container again and give it some updates. I started with the dev branch and noticed that the detect/identify feature in BlueIris no longer works. It stalls out when trying to make a GET request on the local network. Switching back to the master branch works without issue.

@leonowski @TonyBrobston Do you know where in the changes you made could have caused this? Perhaps in the change from running as non-root user or in the run as service changes?

![Screenshot from 2020-11-25 16-05-45](https://user-images.githubusercontent.com/11232787/100281694-61c66c80-2f38-11eb-91c7-80d7a21de915.png)

**Comment by jshridha** [comment]
@leonowski I was able to narrow down the issue to this commit: 290304ab52bbcf246f240cac32d1d47d0ab37dc2

Going back a single commit to: b2dbef945cad250a0a16e07e434c13b651405840 works without a problem.

Can you take a look and see if all of the lines in 290304ab52bbcf246f240cac32d1d47d0ab37dc2 are necessary?

My guess is that the issue is somewhere around lines 9-12 in blueiris.sh

**Comment by jshridha** [comment]
Looks like the problem is here: https://github.com/jshridha/docker-blueiris/blob/f17a63ef6780440b9ef86a5914b03c2ab6e5254b/Dockerfile#L32-L33

Reverting those lines to remove the --install-recommends and the apt upgrade fixes the issue.

@leonowski Can you let me know me know if there are dependencies that you were trying to include for some other issue? Otherwise I will revert those lines to fix the detection issue.

**Comment by jshridha** [comment]
Fixing those lines is no longer a usable fix. Updating the ubuntu base image causes the issue to come back. I believe there's a dependency that is leaking into the wine prefix and causing the issue. Not sure what it is yet though.

**Comment by TonyBrobston** [comment]
@jshridha I can't really add much useful information here. I only tested and gave some feedback, @leonowski did all the development.

I also wasn't aware that there is a detect/identify feature?

**Comment by jshridha** [comment]
@TonyBrobston I figured out the issue and pushed a new commit c3f274b6d5ab333fea37a3905b17a4e3a6c2673c. Thanks for chiming in though!
