### ISSUE TITLE
Wine Microsoft common 6.0.0 issue

### ISSUE THREAD

**Issue by ryanmurray** [jshridha/docker-blueiris#41]
Trying to get this docker working for first time during install on privileged docker it complains of missing Microsoft core 6.0.0

**Comment by ryanmurray** [comment]
Running on gpu docker branch since latest wasn’t working either.

**Comment by jshridha** [comment]
Can you show me your docker run command and the logs?

**Comment by ryanmurray** [comment]
2021-01-07 06:40:25,814 CRIT Supervisor is running as root. Privileges were not dropped because no user is specified in the config file. If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-01-07 06:40:25,816 INFO supervisord started with pid 6
2021-01-07 06:40:26,817 INFO spawned: 'X11' with pid 8
2021-01-07 06:40:26,818 INFO spawned: 'blueiris' with pid 9
2021-01-07 06:40:26,819 INFO spawned: 'fluxbox' with pid 10
2021-01-07 06:40:26,819 INFO spawned: 'novnc' with pid 11
2021-01-07 06:40:26,820 INFO spawned: 'x11vnc' with pid 12
2021-01-07 06:40:27,821 INFO success: X11 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-01-07 06:40:27,821 INFO success: blueiris entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-01-07 06:40:27,821 INFO success: fluxbox entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-01-07 06:40:27,821 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-01-07 06:40:27,821 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by ryanmurray** [comment]
docker run -d \
  --name="blueiris" \
  --privileged \
  --init \
  --restart=always \
  -e TZ=America/Los_Angeles \
  -p 8082:8080 \
  -p 5900:5900 \
  -p 8181:81 \
  -v /mnt/user/appdata/blueiris:/home/wineuser/prefix:rw \
  --log-opt max-size=5m --log-opt max-file=2 \
  jshridha/blueiris

**Comment by ryanmurray** [comment]
./blueiris.sh
002c:fixme:winediag:__wine_start_process Wine Staging 5.11 is a testing version containing experimental patches.
002c:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
0024:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0024:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FEAC
unzip:  cannot find or open /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/ui3.zip, /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/ui3.zip.zip or /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/ui3.zip.ZIP.
wine: cannot find L"/home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/BlueIris.exe"
$ 007c:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
007c:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002

this is what i get trying to run ./blueiris.sh as wineuser

**Comment by ryanmurray** [comment]
running on dev tag instead of gpu

01ac:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
wine: configuration in L"/home/wineuser/prefix" has been updated.
0024:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0240:fixme:explorerframe:taskbar_list_SetProgressValue iface 0013B490, hwnd 00040062, ullCompleted 10000, ullTotal 6c1e00 stub!
07/01/2021 07:16:05 collect_xdamage: too many xdamage events 1000+3406
0240:fixme:explorerframe:taskbar_list_SetProgressState iface 0013B490, hwnd 00040062, flags 0 stub!
0248:fixme:file:NtLockFile I/O completion on lock not implemented yet
0248:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:dwmapi:DwmSetWindowAttribute (00050040, 2, 0031E9F0, 4) stub
0024:fixme:gdiplus:resample_bitmap_pixel Unimplemented interpolation 7
0248:fixme:mpr:WNetGetUniversalNameW (L"", 0x00000001, 025BEA40, 025BE978): stub
0248:fixme:mpr:WNetGetUniversalNameW (L"", 0x00000001, 025BEA40, 025BE978): stub
02e0:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
02e0:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
02e0:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
02e0:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
02e0:fixme:advapi:DecryptFileW (L"C:\\windows\\Temp\\{25A79800-0D9C-41A4-9252-E482E4CDF3FC}\\", 00000000): stub
02ec:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
02ec:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
02ec:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
02ec:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
02ec:fixme:advapi:DecryptFileW (L"C:\\windows\\Temp\\{9C369F15-5A76-4628-9AA2-A792D91351A5}\\", 00000000): stub
02ec:fixme:ver:GetCurrentPackageId (0031FE94 00000000): stub
02e0:fixme:ver:GetCurrentPackageId (0031FE94 00000000): stub
0248:fixme:mpr:WNetGetUniversalNameW (L"C:\\Program Files\\Blue Iris 5", 0x00000001, 025BEB30, 025BEA68): stub
0248:fixme:mpr:WNetGetUniversalNameW (L"C:\\users\\wineuser\\Start Menu\\Programs\\Blue Iris 5", 0x00000001, 025BEB30, 025BEA68): stub
0248:fixme:exec:SHELL_execute flags ignored: 0x00000100
0370:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0370:fixme:file:NtLockFile I/O completion on lock not implemented yet
0370:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0370:fixme:wintrust:SOFTPUB_VerifyImageHash Cannot verify hash for pszObjId="1.3.6.1.4.1.311.2.1.30"
0370:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FEAC
0370:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FEAC
0414:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
0414:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
0414:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
0414:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
0058:fixme:explorer:webbrowser_QueryInterface (000000000041C220)->({00000003-0000-0000-c000-000000000046} 000000000031DCA8) interface not supported
0058:fixme:explorer:webbrowser_QueryInterface (000000000041C220)->({00000003-0000-0000-c000-000000000046} 000000000031DC08) interface not supported
0058:fixme:explorer:webbrowser_QueryInterface (000000000041C220)->({00000019-0000-0000-c000-000000000046} 0000000000032B60) interface not supported
0024:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FEAC
0474:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
Archive: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/ui3.zip
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/launcher-icon.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/loginScripts.js
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/loginStyles.css
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/logos/launcher-icon128.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/logos/launcher-icon128.webp
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/logos/launcher-icon144.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/logos/launcher-icon144.webp
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/logos/launcher-icon168.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/logos/launcher-icon168.webp
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/logos/launcher-icon192.webp
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/logos/launcher-icon48.png
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/logos/launcher-icon72.png
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/logos/launcher-icon96.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/applet/manifest.json
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/clappr/clappr.min.js
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/clappr/LICENSE.txt
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/livestream.htm
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/login.htm
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/airhorn.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/alarm.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/alarm-frenzy.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/alarming.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/alien-message.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/alien-tune.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/are-you-kidding.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/attention-required.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/blocker.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/decay.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/demonstrative.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/determined.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/doorbell.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/enough-with-the-talking.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/gentle-alarm.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/gesture.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/goodbye.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/good-morning.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/hail.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/hell-yeah.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/high-pitch.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/i-demand-attention.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/i-saw-you.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/job-done.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/just-like-magic.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/long-chime-sound.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/may-i-have-your-attention.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/munchausen.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/news-bringer.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/not-kiddin.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/no-way.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/oh-really.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/on-serious-matters.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/paranoid.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/pizzicato.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/police.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/pop.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/professionals.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/quiet-knock.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/robot-walking.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/served.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/sorted.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/springy.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/surprise-on-a-spring.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/system-fault.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/the-squeaky-wheel-gets-the-grease.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/this-is-it.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/warning.mp3

inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/what.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/wiggle.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/will-you.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/sounds/you-wouldnt-believe.mp3
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/timeout.htm
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3.htm
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/ajax-loader-big.gif
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/css-vars-ponyfill.min.js
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/css/bootstrap.min.css
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/css/help.css
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/help.html
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/BetterLayout.jpg
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/CameraContextMenu.png
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/ClipContextMenu.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/ConvertExport.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/ConvertExportIcon.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/ExportList.png
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/ExportRange.png
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/ExportStatus.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/GroupProperties.png
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/MainMenuIcon.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/PoorLayout.jpg
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/ProfileEditor.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/RecordingFilters.png
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/img/StatsForNerds.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/js/bootstrap.min.js
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/js/help.js
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/js/jquery.stickytabs.js
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/help/js/jquery-1.12.4.min.js
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/horror.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/icons.svg
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/launcher-icon.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/libs-ui3.css
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/libs-ui3.js
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/licenses.txt
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/LoadingImage.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/logos/launcher-icon128.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/logos/launcher-icon128.webp
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/logos/launcher-icon144.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/logos/launcher-icon144.webp
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/logos/launcher-icon168.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/logos/launcher-icon168.webp
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/logos/launcher-icon192.webp
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/logos/launcher-icon48.png
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/logos/launcher-icon72.png
extracting: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/logos/launcher-icon96.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/logos/overlay96.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/logos/overlay96.webp
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/manifest.json
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/noimage.png
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/openh264_decoder.js
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/pnacl/pnacl_player.nmf
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/pnacl/pnacl_player.pexe
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/reset.htm
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/svgtest.htm
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/ui3.css
inflating: /home/wineuser/prefix/drive_c/Program Files/Blue Iris 5/www/ui3/ui3.js
0474:err:module:import_dll Library mfc140u.dll (which is needed by L"C:\\Program Files\\Blue Iris 5\\BlueIris.exe") not found
0474:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files\\Blue Iris 5\\BlueIris.exe" failed, status c0000135

0078:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0078:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0078:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0078:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
00c8:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
2021-01-07 07:16:32,576 WARN received SIGTERM indicating exit request
2021-01-07 07:16:32,576 INFO waiting for X11, blueiris, fluxbox, novnc, x11vnc to die
caught signal: 15
07/01/2021 07:16:32 deleted 32 tile_row polling images.
07/01/2021 07:16:32 Restored X server key autorepeat to: 1
2021-01-07 07:16:32,578 INFO stopped: x11vnc (exit status 2)

Terminating WebSockets proxy (21)
00c8:err:module:import_dll Library mfc140u.dll (which is needed by L"C:\\Program Files\\Blue Iris 5\\BlueIris.exe") not found
2021-01-07 07:16:32,621 INFO stopped: novnc (exit status 143)
2021-01-07 07:16:32,668 INFO stopped: fluxbox (exit status 0)
00c8:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files\\Blue Iris 5\\BlueIris.exe" failed, status c0000135

2021-01-07 07:16:32,695 INFO stopped: blueiris (terminated by SIGTERM)
2021-01-07 07:16:33,030 INFO stopped: X11 (exit status 0)

Acutally got to install this time but then can't run.

**Comment by ryanmurray** [comment]
Seems to be related to home/wineuser/prefix not being owned, I’ve tried this with a mapped path and a docker volume but to no success. I am on unraid but attempting to run the docker build command from command line.

**Comment by ryanmurray** [comment]
i was able to get permissions to work on a docker volume. For some reason when docker builds and runs root still owns wineuser/prefix even with privleged command passed. I did end up getting it working on latest dev after fighting a couple days got my camera setup and remote access working. Coming from shinobi i am pleased how much easier blue iris is to use.

**Comment by jshridha** [comment]
@ryanmurray Awesome news! Yes you'll need to set the permissions before the first bootup. I need to fix this in the startup script. Shouldn't be a hard fix.

I'm going to close this issue, but feel free to reopen it.

**Comment by extremeshok** [comment]
wine: /home/wineuser/prefix is not owned by you still persists
