### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by reesericci** [jshridha/docker-blueiris#45]
Why is this docker container using WINE to run BI when microsoft publishes windows docker images? Just install BI in the windows docker container and enable RDP.

Is this possible?

-- Reese

**Comment by jshridha** [comment]
This would be awesome, but my understanding is even though those containers are multiarch, they are required to run in Windows server installations. The goal of this container is to run on linux hosts rather than windows hosts.

**Comment by ycodryn** [comment]
And running on linux host will eat less resources than windows hosts. Is like this: docker is on linux kernel, so windows will create inside container a vm anyway to run on it > resource heavy

**Comment by reesericci** [comment]
> This would be awesome, but my understanding is even though those containers are multiarch, they are required to run in Windows server installations. The goal of this container is to run on linux hosts rather than windows hosts.

Ah, that makes total sense.
