### ISSUE TITLE
Black screen when mounting a ssd

### ISSUE THREAD

**Issue by pjrt** [jshridha/docker-blueiris#50]
I am mounting my ssd on `/root/prefix32` as the README states, but when I do that, the vnc interface is blank (it manages to connect though). 

If I do not mount anything, then the vnc (eventually) shows wine getting configured and eventually BlueIris. 

Any idea what's going on? This is the blkid for that drive:

```
UUID="84D5-0848" BLOCK_SIZE="512" TYPE="exfat" PTTYPE="dos"
```

**Comment by pjrt** [comment]
I remade the ssd with an `ntfs` filesystem and it seems to now work.

**Comment by jshridha** [comment]
The file system shouldn't matter. It's likely an issue with permissions on the prefix folder. Check out the gpu branch. It has a fix for setting the permissions on first setup.
