### ISSUE TITLE
Log flooded with fixme:variant:get_date_format ignoring flags 402

### ISSUE THREAD

**Issue by anonymous-one** [jshridha/docker-blueiris#54]
Before I begin, thank you very much for the great project. Early times, but so far its looking like in my use case its stable. I just had it up for about 4 hours and so far what I need it to do (motion -> url alert -> save clip) all works great.

One issue I am having is:

My docker log is being filled with `fixme:variant:get_date_format ignoring flags 402`.

Any ideas why this is / how to at least hide this?

Thanks!

EDIT : I am running the :dev tag, released Feb 2021.

**Comment by anonymous-one** [comment]
Alright well I'm fairly new to wine and docker... But I was able to hide all of the wine fixmes by exporting `WINEDEBUG=-all`.

This will make deubgging things a pain if ever need be, but at least the log doesn't get so stuffed. After about 4 hours it had about 150000 entries.

**Comment by anonymous-one** [comment]
I'm now a little more versed in this and see this has been resolved in the GPU tag. Wine is still spitting out those errors but supervisord is set up not to log so dockers logs don't get flooded.

**Comment by CalebFenton** [comment]
@anonymous-one Thanks for posting a workaround and hinting at a true fix, but what is "GPU tag"? Is that a version of wine?
