### ISSUE TITLE
TimeZone Problems

### ISSUE THREAD

**Issue by GettingTechnicl** [jshridha/docker-blueiris#57]
Good morning,

I've been utilizing blueiris in a docker for the past few months, throughout this time my timeline has been incorrect in blueiris. It is 6 hours ahead exactly, therefore I have been utilizing the camera overlay on the image so the camera streams display the proper time, although I would prefer to use blueiris for the overlay. 

I would also love to have the timeline displaying the correct time, so I've been digging in to this a bit lately. 

I initially ran the master branch, followed by the dev branch, and now the gpu branch. I've only switched to the dev and gpu branches as I saw the creator of this claim the time issues were fixed in these versions quite some time ago. 

I have the following variables passed in my buildfile in an attempt to correct the time. 
-e TZ=America/Chicago
-v /etc/localtime:/etc/localtime:ro
-v /etc/timezone:/etc/timezone:ro
... None of these work or I wouldn't be here. 

I have also tried the following wine registry edit
docker exec -it <container_name> /bin/bash
wine reg add 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\TimeZoneInformation' /v TimeZoneKeyName /t REG_SZ /d 'Central Standard Time' /f

Also checking the time and timezone in the docker using any time commands I've been able to find, all display that the time is set to CST or America/Chicago

I'd really love to get this resolved, if anyone could let me know how they have resolved this, or if people are just dealing with it...

**Comment by hoyane** [comment]
If you use only the two volume links and remove the TZ variable it should work. TZ seems to do nothing on this docker.

**Comment by GettingTechnicl** [comment]
> If you use only the two volume links and remove the TZ variable it should work. TZ seems to do nothing on this docker.

Works! Thanks!

**Comment by justincrich** [comment]
This helped me solve the problem ☝️
