### ISSUE TITLE
Setting Time

### ISSUE THREAD

**Issue by dinki** [jshridha/docker-blueiris#6]
I cannot for the life of me figure out how to set time on this container.  

I've tried passing TZ=America/Chicago as an environment variable when running the container.  

I've tried linking /etc/timezone to /usr/share/zoneinfo/America/Chicago .  

The date appears to be correct if I do an exec bash on the container but despite all this, my timestamps show up as UTC.

Can someone tell me how to set time?  Thanks

**Comment by dinki** [comment]
Still banging my head on this.  Can someone PLEASE offer some insight on getting this set?

**Comment by dinki** [comment]
Hey guys!!!  Back again!  Time appears to work GREAT in UI3 but not in the timestamps on the overlay.  Can someone confirm that this is working for them?  Otherwise I create an issue (for what it's worth).

**Comment by jshridha** [comment]
Try linking like this:

``` -v /etc/localtime:/etc/localtime:ro ```

**Comment by calvinbui** [comment]
> Try linking like this:
> 
> `-v /etc/localtime:/etc/localtime:ro`

Still shows as UTC for me within the application

**Comment by jshridha** [comment]
@calvinbui What host OS are you using and what timezone is it set to?

**Comment by calvinbui** [comment]
i must've done something wrong the first time as it's working now.

**Comment by Viksie** [comment]
Can anyone provide any clarity on this issue ?

I've removed the symlink /etc/localtime. Passed -v /etc/localtime:/etc/localtime:ro in the compose file. Added and removed locales. Updated all components. Now even rebuild the container.

The container's local time is reflecting the timezone correctly, yet BlueIris v5 simply remains  fixated on UTC+0, be it in the overlay, UI3 or VNC session.
